# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("testapp", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="UserLoginActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("login_IP", models.GenericIPAddressField(blank=True, null=True)),
                ("login_datetime", models.DateTimeField(auto_now=True)),
                (
                    "login_username",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("S", "Success"), ("F", "Failed")],
                        default="S",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("user_agent_info", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user_login_activity",
                "verbose_name_plural": "user_login_activities",
            },
        )
    ]
