# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("testapp", "0002_userloginactivity")]

    operations = [
        migrations.RemoveField(model_name="userloginactivity", name="username")
    ]
