# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testapp", "0003_remove_userloginactivity_username")]

    operations = [
        migrations.RemoveField(model_name="userloginactivity", name="status"),
        migrations.AddField(
            model_name="userloginactivity",
            name="login_success",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
