# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testapp", "0004_auto_20190911_0920")]

    operations = [
        migrations.AddField(
            model_name="userloginactivity",
            name="errors",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
