# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testapp", "0005_userloginactivity_errors")]

    operations = [
        migrations.AddField(
            model_name="userloginactivity",
            name="stage",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        )
    ]
